package model.pojo;
// Generated 19.04.2018 15:05:11 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Job generated by hbm2java
 */
public class Job  implements java.io.Serializable {


     private Integer idJob;
     private User user;
     private String body;
     private Date startDate;
     private Date endDate;
     private Date deadline;

    public Job() {
    }

	
    public Job(String body, Date deadline) {
        this.body = body;
        this.deadline = deadline;
    }
    public Job(User user, String body, Date startDate, Date endDate, Date deadline) {
       this.user = user;
       this.body = body;
       this.startDate = startDate;
       this.endDate = endDate;
       this.deadline = deadline;
    }
   
    public Integer getIdJob() {
        return this.idJob;
    }
    
    public void setIdJob(Integer idJob) {
        this.idJob = idJob;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getBody() {
        return this.body;
    }
    
    public void setBody(String body) {
        this.body = body;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public Date getDeadline() {
        return this.deadline;
    }
    
    public void setDeadline(Date deadline) {
        this.deadline = deadline;
    }




}


