package model.pojo;
// Generated 19.04.2018 15:05:11 by Hibernate Tools 4.3.1



/**
 * Profile generated by hbm2java
 */
public class Profile  implements java.io.Serializable {


     private Integer idProfile;
     private User user;
     private String name;
     private String surname;
     private String specialization;
     private String about;

    public Profile() {
    }

	
    public Profile(User user) {
        this.user = user;
    }
    public Profile(User user, String name, String surname, String specialization, String about) {
       this.user = user;
       this.name = name;
       this.surname = surname;
       this.specialization = specialization;
       this.about = about;
    }
   
    public Integer getIdProfile() {
        return this.idProfile;
    }
    
    public void setIdProfile(Integer idProfile) {
        this.idProfile = idProfile;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getSpecialization() {
        return this.specialization;
    }
    
    public void setSpecialization(String specialization) {
        this.specialization = specialization;
    }
    public String getAbout() {
        return this.about;
    }
    
    public void setAbout(String about) {
        this.about = about;
    }




}


