package model.pojo;
// Generated 19.04.2018 15:05:11 by Hibernate Tools 4.3.1



/**
 * RequestFert generated by hbm2java
 */
public class RequestFert  implements java.io.Serializable {


     private Integer idRequestFert;
     private User user;
     private String fertName;
     private int quantity;
     private String body;
     private int status;

    public RequestFert() {
    }

	
    public RequestFert(User user, String fertName, int quantity) {
        this.user = user;
        this.fertName = fertName;
        this.quantity = quantity;
    }
    public RequestFert(User user, String fertName, int quantity, String body) {
       this.user = user;
       this.fertName = fertName;
       this.quantity = quantity;
       this.body = body;
    }
   
    public Integer getIdRequestFert() {
        return this.idRequestFert;
    }
    
    public void setIdRequestFert(Integer idRequestFert) {
        this.idRequestFert = idRequestFert;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getFertName() {
        return this.fertName;
    }
    
    public void setFertName(String fertName) {
        this.fertName = fertName;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public String getBody() {
        return this.body;
    }
    
    public void setBody(String body) {
        this.body = body;
    }

    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }


}


