package model.pojo;
// Generated 19.04.2018 15:05:11 by Hibernate Tools 4.3.1



/**
 * RequestTree generated by hbm2java
 */
public class RequestTree  implements java.io.Serializable {


     private Integer idRequestTree;
     private Tree tree;
     private User user;
     private int quantity;
     private String body;

    public RequestTree() {
    }

	
    public RequestTree(Tree tree, User user, int quantity) {
        this.tree = tree;
        this.user = user;
        this.quantity = quantity;
    }
    public RequestTree(Tree tree, User user, int quantity, String body) {
       this.tree = tree;
       this.user = user;
       this.quantity = quantity;
       this.body = body;
    }
   
    public Integer getIdRequestTree() {
        return this.idRequestTree;
    }
    
    public void setIdRequestTree(Integer idRequestTree) {
        this.idRequestTree = idRequestTree;
    }
    public Tree getTree() {
        return this.tree;
    }
    
    public void setTree(Tree tree) {
        this.tree = tree;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public String getBody() {
        return this.body;
    }
    
    public void setBody(String body) {
        this.body = body;
    }




}


