package model.pojo;
// Generated 19.04.2018 15:05:11 by Hibernate Tools 4.3.1



/**
 * Sector generated by hbm2java
 */
public class Sector  implements java.io.Serializable {


     private Integer idSector;
     private Soil soil;
     private Tree tree;
     private double square;

    public Sector() {
    }

	
    public Sector(Soil soil, double square) {
        this.soil = soil;
        this.square = square;
    }
    public Sector(Soil soil, Tree tree, double square) {
       this.soil = soil;
       this.tree = tree;
       this.square = square;
    }
   
    public Integer getIdSector() {
        return this.idSector;
    }
    
    public void setIdSector(Integer idSector) {
        this.idSector = idSector;
    }
    public Soil getSoil() {
        return this.soil;
    }
    
    public void setSoil(Soil soil) {
        this.soil = soil;
    }
    public Tree getTree() {
        return this.tree;
    }
    
    public void setTree(Tree tree) {
        this.tree = tree;
    }
    public double getSquare() {
        return this.square;
    }
    
    public void setSquare(double square) {
        this.square = square;
    }




}


