package model.pojo;
// Generated 19.04.2018 15:05:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Soil generated by hbm2java
 */
public class Soil  implements java.io.Serializable {


     private Integer idSoil;
     private int humus;
     private int acidity;
     private int nitrate;
     private int phosphor;
     private Set sectors = new HashSet(0);

    public Soil() {
    }

	
    public Soil(int humus, int acidity, int nitrate, int phosphor) {
        this.humus = humus;
        this.acidity = acidity;
        this.nitrate = nitrate;
        this.phosphor = phosphor;
    }
    public Soil(int humus, int acidity, int nitrate, int phosphor, Set sectors) {
       this.humus = humus;
       this.acidity = acidity;
       this.nitrate = nitrate;
       this.phosphor = phosphor;
       this.sectors = sectors;
    }
   
    public Integer getIdSoil() {
        return this.idSoil;
    }
    
    public void setIdSoil(Integer idSoil) {
        this.idSoil = idSoil;
    }
    public int getHumus() {
        return this.humus;
    }
    
    public void setHumus(int humus) {
        this.humus = humus;
    }
    public int getAcidity() {
        return this.acidity;
    }
    
    public void setAcidity(int acidity) {
        this.acidity = acidity;
    }
    public int getNitrate() {
        return this.nitrate;
    }
    
    public void setNitrate(int nitrate) {
        this.nitrate = nitrate;
    }
    public int getPhosphor() {
        return this.phosphor;
    }
    
    public void setPhosphor(int phosphor) {
        this.phosphor = phosphor;
    }
    public Set getSectors() {
        return this.sectors;
    }
    
    public void setSectors(Set sectors) {
        this.sectors = sectors;
    }




}


