package model.pojo;
// Generated 19.04.2018 15:05:11 by Hibernate Tools 4.3.1



/**
 * Tour generated by hbm2java
 */
public class Tour  implements java.io.Serializable {


     private Integer idTour;
     private String body;
     private double price;
     private String startDate;
     private String endDate;

    public Tour() {
    }

    public Tour(String body, double price, String startDate, String endDate) {
       this.body = body;
       this.price = price;
       this.startDate = startDate;
       this.endDate = endDate;
    }
   
    public Integer getIdTour() {
        return this.idTour;
    }
    
    public void setIdTour(Integer idTour) {
        this.idTour = idTour;
    }
    public String getBody() {
        return this.body;
    }
    
    public void setBody(String body) {
        this.body = body;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }
    public String getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(String startDate) {
        this.startDate = startDate;
    }
    public String getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(String endDate) {
        this.endDate = endDate;
    }




}


