package model.pojo;
// Generated 19.04.2018 15:05:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tree generated by hbm2java
 */
public class Tree  implements java.io.Serializable {


     private Integer idTree;
     private String name;
     private String body;
     private int optHumus;
     private int optAcidity;
     private int optNitrate;
     private int optPhosphor;
     private Set sectors = new HashSet(0);
     private Set requestTrees = new HashSet(0);

    public Tree() {
    }

	
    public Tree(String name, int optHumus, int optAcidity, int optNitrate, int optPhosphor) {
        this.name = name;
        this.optHumus = optHumus;
        this.optAcidity = optAcidity;
        this.optNitrate = optNitrate;
        this.optPhosphor = optPhosphor;
    }
    public Tree(String name, String body, int optHumus, int optAcidity, int optNitrate, int optPhosphor, Set sectors, Set requestTrees) {
       this.name = name;
       this.body = body;
       this.optHumus = optHumus;
       this.optAcidity = optAcidity;
       this.optNitrate = optNitrate;
       this.optPhosphor = optPhosphor;
       this.sectors = sectors;
       this.requestTrees = requestTrees;
    }
   
    public Integer getIdTree() {
        return this.idTree;
    }
    
    public void setIdTree(Integer idTree) {
        this.idTree = idTree;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getBody() {
        return this.body;
    }
    
    public void setBody(String body) {
        this.body = body;
    }
    public int getOptHumus() {
        return this.optHumus;
    }
    
    public void setOptHumus(int optHumus) {
        this.optHumus = optHumus;
    }
    public int getOptAcidity() {
        return this.optAcidity;
    }
    
    public void setOptAcidity(int optAcidity) {
        this.optAcidity = optAcidity;
    }
    public int getOptNitrate() {
        return this.optNitrate;
    }
    
    public void setOptNitrate(int optNitrate) {
        this.optNitrate = optNitrate;
    }
    public int getOptPhosphor() {
        return this.optPhosphor;
    }
    
    public void setOptPhosphor(int optPhosphor) {
        this.optPhosphor = optPhosphor;
    }
    public Set getSectors() {
        return this.sectors;
    }
    
    public void setSectors(Set sectors) {
        this.sectors = sectors;
    }
    public Set getRequestTrees() {
        return this.requestTrees;
    }
    
    public void setRequestTrees(Set requestTrees) {
        this.requestTrees = requestTrees;
    }




}


